# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest
import torch
from gguf import GGUFReader

from vllm import LLM, SamplingParams

from vllm_gguf_plugin.hadamard import read_prism_hadamard_config


GGUF_ENV = "PRISM_GGUF"
TOKENIZER_ENV = "PRISM_TOKENIZER"
REFERENCE_ENV = "PRISM_REFERENCE_JSON"


def _require_env(name: str) -> str:
    value = os.environ.get(name)

    if not value:
        pytest.skip(
            f"{name} is not set; "
            "this test requires a real Prism GGUF model"
        )

    return value


def _get_tensor_names(path: str) -> set[str]:
    reader = GGUFReader(path)

    return {
        tensor.name
        for tensor in reader.tensors
    }


def _load_reference() -> dict:
    path = _require_env(REFERENCE_ENV)

    with open(path, encoding="utf-8") as f:
        return json.load(f)


@pytest.mark.slow
def test_prism_tied_output_metadata():
    gguf_path = _require_env(GGUF_ENV)

    hcfg = read_prism_hadamard_config(
        gguf_path
    )

    assert hcfg is not None

    if not hcfg.tied_output:
        pytest.skip(
            "PRISM_GGUF is not a tied-output Prism model"
        )

    tensor_names = _get_tensor_names(
        gguf_path
    )

    assert hcfg.version == 2

    assert "token_embd.weight" in (
        hcfg.inverse_weight_names
    )

    assert "output.weight" not in tensor_names

@pytest.mark.slow
def test_prism_model_hadamard_metadata():
    gguf_path = _require_env(GGUF_ENV)

    hcfg = read_prism_hadamard_config(
        gguf_path
    )

    assert hcfg is not None

    tensor_names = _get_tensor_names(
        gguf_path
    )

    assert "token_embd.weight" in tensor_names

    # Embeddings are stored in the latent/Hadamard basis
    # and must be inverse-transformed after lookup.
    assert "token_embd.weight" in (
        hcfg.inverse_weight_names
    )

    if hcfg.tied_output:
        # Tied topology:
        #
        #   token_embd.weight is physically shared with
        #   the output head.
        #
        # There must be no independent output tensor.
        assert hcfg.version == 2
        assert "output.weight" not in tensor_names

    else:
        # Untied topology:
        #
        #   output.weight exists independently and was
        #   forward-folded during Prism conversion.
        assert hcfg.version == 1
        assert "output.weight" in tensor_names
        assert "output.weight" in hcfg.weight_names


@pytest.mark.slow
def test_prism_model_end_to_end_correctness():
    """
    Run the entire Prism GGUF through vLLM's normal model-loading and
    inference path.

    This catches failures in:

        metadata parsing
        GGUF -> vLLM name mapping
        PQ2 dequantization
        GDN V permutation
        sign application
        FWHT
        inverse embedding transform
        tied LM-head forward transform
        final logits

    The reference JSON should be generated by Prism/llama.cpp from the same
    GGUF and the same prompt token IDs.
    """

    gguf_path = _require_env(GGUF_ENV)
    tokenizer = _require_env(TOKENIZER_ENV)

    reference = _load_reference()

    prompt_token_ids = reference[
        "prompt_token_ids"
    ]

    expected_token_ids = reference[
        "generated_token_ids"
    ]

    expected_logprobs = reference.get(
        "generated_logprobs"
    )

    max_tokens = len(
        expected_token_ids
    )

    assert max_tokens > 0

    llm = LLM(
        model=gguf_path,
        tokenizer=tokenizer,

        # Keep this first correctness test simple.
        tensor_parallel_size=1,

        # Avoid CUDA graph issues while bringing up
        # the transform path.
        enforce_eager=True,

        # Avoid unnecessary memory reservation.
        gpu_memory_utilization=0.80,

        # Make test deterministic.
        seed=0,

        max_model_len=4096,


        language_model_only=True,

    )

    sampling_params = SamplingParams(
        temperature=0.0,
        max_tokens=max_tokens,

        # We need logprobs to catch cases where the
        # greedy token happens to match even though
        # logits differ.
        logprobs=20,

        # Do not stop early if the golden run contains
        # tokens after EOS.
        ignore_eos=True,
    )

    outputs = llm.generate(
        [
            {
                "prompt_token_ids":
                    prompt_token_ids,
            }
        ],
        sampling_params,
        use_tqdm=False,
    )

    assert len(outputs) == 1
    assert len(outputs[0].outputs) == 1

    result = outputs[0].outputs[0]

    print("token:", out.token_ids[0])
    
    for token_id, lp in out.logprobs[0].items():
        print(
            token_id,
            lp.logprob,
            getattr(lp, "decoded_token", None),
        )


    got_token_ids = list(
        result.token_ids
    )

    assert got_token_ids == expected_token_ids, (
        "\nPrism/vLLM generated token mismatch\n"
        f"expected: {expected_token_ids}\n"
        f"got:      {got_token_ids}\n"
    )

    if expected_logprobs is not None:
        _assert_generated_logprobs_close(
            result,
            expected_token_ids,
            expected_logprobs,
        )


def _assert_generated_logprobs_close(
    result,
    expected_token_ids: list[int],
    expected_logprobs: list[float],
    *,
    atol: float = 2e-2,
    rtol: float = 2e-2,
) -> None:
    """
    Compare the logprob assigned to the actual generated token at each step.

    We intentionally do not require equality of the entire vocabulary
    distribution here. That would require exporting full logits from both
    engines and is much heavier than needed for the initial integration test.
    """

    assert result.logprobs is not None

    assert len(result.logprobs) == len(
        expected_token_ids
    )

    assert len(expected_logprobs) == len(
        expected_token_ids
    )

    got_logprobs = []

    for step, token_id in enumerate(
        expected_token_ids
    ):
        step_logprobs = result.logprobs[
            step
        ]

        assert token_id in step_logprobs, (
            f"generated token {token_id} "
            f"missing from logprobs at step {step}"
        )

        lp = step_logprobs[token_id]

        # vLLM Logprob object
        got_logprobs.append(
            float(lp.logprob)
        )

    got = torch.tensor(
        got_logprobs,
        dtype=torch.float64,
    )

    expected = torch.tensor(
        expected_logprobs,
        dtype=torch.float64,
    )

    torch.testing.assert_close(
        got,
        expected,
        atol=atol,
        rtol=rtol,
    )
